import { useMemo,useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Plus,Search } from "lucide-react";
import { controlApi } from "../api/control";
import { useAuth } from "../auth/AuthContext";
import { Panel } from "../components/Panel";
import { StatusBadge } from "../components/StatusBadge";
import { Topbar } from "../components/Topbar";
import { formatDateTime } from "../lib/time";
function tone(l:string){if(l==="COMMISSIONED")return "healthy";if(l==="SUSPENDED"||l==="RETIRED")return "offline";return "warning"}
export function CommissioningPage(){const auth=useAuth();const [query,setQuery]=useState("");const q=useQuery({queryKey:["commissionings"],queryFn:controlApi.commissionings,refetchInterval:10000});const rows=useMemo(()=>{const n=query.trim().toLowerCase();return(q.data??[]).filter(c=>!n||[c.tag,c.name,c.siteId,c.stage,c.lifecycle].some(v=>v.toLowerCase().includes(n)))},[q.data,query]);return <><Topbar title="Commissioning" subtitle="Ativos ainda não promovidos ficam fora da frota operacional" onRefresh={()=>void q.refetch()} refreshing={q.isFetching}>{auth.hasPermission("commissioning.write")?<Link className="primary-button compact" to="/engineering/commissioning/new"><Plus/>Adicionar gerador</Link>:null}</Topbar><div className="content-grid"><section className="quality-strip"><div><span>Regra</span><strong>DRAFT/COMMISSIONING ≠ OFFLINE</strong></div><div><span>Promoção</span><strong>somente após todos os gates PASS</strong></div><div><span>Escrita industrial</span><strong>DESABILITADA</strong></div></section><Panel title={`Fila (${rows.length})`} action={<label className="mini-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar ativo/etapa"/></label>}><div className="table-wrap"><table className="data-table"><thead><tr><th>Ativo</th><th>Site</th><th>Lifecycle</th><th>Etapa</th><th>Gates</th><th>Atualizado</th><th/></tr></thead><tbody>{rows.map(c=>{const pass=Object.values(c.gates).filter(g=>g.status==="PASS").length;return <tr key={c.id}><td><strong>{c.tag}</strong><br/><small>{c.name}</small></td><td>{c.siteId}</td><td><StatusBadge tone={tone(c.lifecycle)}>{c.lifecycle}</StatusBadge></td><td><code>{c.stage}</code></td><td>{pass}/{Object.keys(c.gates).length}</td><td>{formatDateTime(c.updatedAt)}</td><td><Link to={`/engineering/commissioning/${c.id}`}>Abrir ↗</Link></td></tr>})}</tbody></table></div>{rows.length===0?<p className="empty">Nenhum commissioning no escopo atual.</p>:null}</Panel></div></>}
