import { useMemo,useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "react-router-dom";
import { Search } from "lucide-react";
import { controlApi } from "../api/control";
import { Panel } from "../components/Panel";
import { StatusBadge } from "../components/StatusBadge";
import { Topbar } from "../components/Topbar";
import { controllerImageSrc, CONTROLLER_IMAGE_FALLBACK } from "../lib/controllerImage";
function tone(status:string){return status==="HOMOLOGATED"||status==="HIL_VALIDATED"?"healthy":status==="DEPRECATED"?"offline":status==="LAB"?"warning":"unknown"}
export function ProfilesPage(){const [query,setQuery]=useState("");const q=useQuery({queryKey:["profiles"],queryFn:controlApi.profiles});const states=useQuery({queryKey:["profile-states"],queryFn:controlApi.profileStates});const stateMap=useMemo(()=>new Map((states.data??[]).map(x=>[x.profileId,x])),[states.data]);const rows=useMemo(()=>{const n=query.toLowerCase().trim();return (q.data?.profiles??[]).filter(p=>!n||[p.id,p.manufacturer,p.model,p.displayName,stateMap.get(p.id)?.status??"DRAFT"].some(x=>x.toLowerCase().includes(n)))},[q.data,query,stateMap]);return <><Topbar title="Controladoras / Profiles" subtitle="Catálogo versionado + qualificação auditada" onRefresh={()=>{void q.refetch();void states.refetch()}} refreshing={q.isFetching||states.isFetching}/><div className="content-grid"><div className="info-banner">Status HIL/HOMOLOGATED nunca é inferido por software. Exige evidência humana/externa e continua separado de PRODUCTION_VALIDATED.</div><Panel title={`Profiles (${rows.length})`} action={<label className="mini-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar profile/status"/></label>}><div className="profile-grid">{rows.map(profile=>{const state=stateMap.get(profile.id);const status=state?.status??"DRAFT";return <article className="profile-card profile-card-with-image" key={profile.id}><header><div><h3>{profile.displayName}</h3><code>{profile.id}</code></div><StatusBadge tone={tone(status)}>{status}</StatusBadge></header><div className="profile-controller-row"><img src={controllerImageSrc(profile.model)} alt={`${profile.manufacturer} ${profile.model}`} onError={e=>{e.currentTarget.src=CONTROLLER_IMAGE_FALLBACK}}/><div><p><strong>{profile.manufacturer}</strong></p><p>{profile.model}</p>{state?.version?<small>Qualificação: {state.version}</small>:null}</div></div><div className="profile-counts"><span>{profile.metrics.length} métricas declaradas</span><span>{profile.alarms.length} alarmes</span></div><footer><span>Remote control: <strong>DISABLED</strong></span><Link to={`/engineering/profiles/${encodeURIComponent(profile.id)}`}>Detalhes ↗</Link></footer></article>})}</div></Panel></div></>}
