import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { controlApi, type Preferences, type Settings } from "../api/control";
import { useAuth } from "../auth/AuthContext";
import { Panel } from "../components/Panel";
import { Topbar } from "../components/Topbar";
export function SettingsPage() {
  const auth = useAuth(); const qc = useQueryClient(); const prefQ = useQuery({ queryKey: ["preferences"], queryFn: controlApi.preferences }); const settingsQ = useQuery({ queryKey: ["settings"], queryFn: controlApi.settings, enabled: auth.hasPermission("settings.read") });
  const [pref, setPref] = useState<Preferences>({ language:"pt-BR", timeZone:"America/Sao_Paulo", unitSystem:"metric", fleetView:"vertical" });
  const [settings, setSettings] = useState<Settings>({ defaultLanguage:"pt-BR", defaultTimeZone:"America/Sao_Paulo", defaultFleetView:"vertical" }); const [message,setMessage]=useState("");
  useEffect(()=>{ if(prefQ.data) setPref(prefQ.data); },[prefQ.data]); useEffect(()=>{ if(settingsQ.data) setSettings(settingsQ.data); },[settingsQ.data]);
  const savePref=async()=>{try{await controlApi.updatePreferences(auth.csrf,pref);await auth.refresh();setMessage("Preferências salvas.");void qc.invalidateQueries({queryKey:["preferences"]})}catch(e){setMessage(e instanceof Error?e.message:"Falha")}};
  const saveSettings=async()=>{try{await controlApi.updateSettings(auth.csrf,settings);setMessage("Padrões globais salvos e auditados.");void settingsQ.refetch()}catch(e){setMessage(e instanceof Error?e.message:"Falha")}};
  return <><Topbar title="Configurações" subtitle="Preferências pessoais e padrões administrativos"/><div className="content-grid">{message?<div className="info-banner">{message}</div>:null}<div className="two-col"><Panel title="Minha interface"><div className="stack-form"><label>Idioma<select value={pref.language} onChange={e=>setPref({...pref,language:e.target.value as Preferences["language"]})}><option value="pt-BR">Português (Brasil)</option><option value="en-US">English (US)</option></select></label><label>Timezone<input value={pref.timeZone} onChange={e=>setPref({...pref,timeZone:e.target.value})}/></label><label>Unidades<select value={pref.unitSystem} onChange={e=>setPref({...pref,unitSystem:e.target.value as Preferences["unitSystem"]})}><option value="metric">Métrico</option><option value="imperial">Imperial</option></select></label><label>Visualização padrão da frota<select value={pref.fleetView} onChange={e=>setPref({...pref,fleetView:e.target.value as Preferences["fleetView"]})}><option value="vertical">Vertical</option><option value="compact">Compacto</option><option value="list">Lista</option></select></label><button className="primary-button" onClick={()=>void savePref()}>Salvar preferências</button></div></Panel>{auth.hasPermission("settings.read")?<Panel title="Padrões do sistema"><div className="stack-form"><label>Idioma padrão<select disabled={!auth.hasPermission("settings.write")} value={settings.defaultLanguage} onChange={e=>setSettings({...settings,defaultLanguage:e.target.value as Settings["defaultLanguage"]})}><option value="pt-BR">Português (Brasil)</option><option value="en-US">English (US)</option></select></label><label>Timezone padrão<input disabled={!auth.hasPermission("settings.write")} value={settings.defaultTimeZone} onChange={e=>setSettings({...settings,defaultTimeZone:e.target.value})}/></label><label>Frota padrão<select disabled={!auth.hasPermission("settings.write")} value={settings.defaultFleetView} onChange={e=>setSettings({...settings,defaultFleetView:e.target.value as Settings["defaultFleetView"]})}><option value="vertical">Vertical</option><option value="compact">Compacto</option><option value="list">Lista</option></select></label>{auth.hasPermission("settings.write")?<button className="primary-button" onClick={()=>void saveSettings()}>Salvar padrões globais</button>:null}<p className="panel-note">Políticas de senha, MFA obrigatório para Administrator/Commissioning Engineer, CSRF e comandos industriais bloqueados não são relaxadas por esta tela.</p></div></Panel>:null}</div></div></>;
}
