import { ProfileDetailPage } from "./pages/ProfileDetailPage";
import { AboutPage } from "./pages/AboutPage";
import { BindingsPage } from "./pages/BindingsPage";
import { RolesPage } from "./pages/RolesPage";
import { SettingsPage } from "./pages/SettingsPage";
import { HistoryPage } from "./pages/HistoryPage";
import { Navigate,Route,Routes } from "react-router-dom";
import { RequireAuth,RequirePermission } from "./auth/RequireAuth";
import { AppShell } from "./components/AppShell";
import { AlarmsPage } from "./pages/AlarmsPage";import { AuditPage } from "./pages/AuditPage";import { CommissioningDetailPage } from "./pages/CommissioningDetailPage";
import { CommissioningEditPage } from "./pages/CommissioningEditPage";import { CommissioningPage } from "./pages/CommissioningPage";import { CommunicationPage } from "./pages/CommunicationPage";import { DiagnosticsPage } from "./pages/DiagnosticsPage";import { EventsPage } from "./pages/EventsPage";import { ForbiddenPage } from "./pages/ForbiddenPage";import { GeneratorDetailPage } from "./pages/GeneratorDetailPage";import { GeneratorsPage } from "./pages/GeneratorsPage";import { LoginPage } from "./pages/LoginPage";import { NewCommissioningPage } from "./pages/NewCommissioningPage";import { OverviewPage } from "./pages/OverviewPage";import { ProfilesPage } from "./pages/ProfilesPage";import { SecurityPage } from "./pages/SecurityPage";import { SitesPage } from "./pages/SitesPage";import { SystemAdminPage } from "./pages/SystemAdminPage";import { UsersPage } from "./pages/UsersPage";
export function App(){return <Routes><Route path="/login" element={<LoginPage/>}/><Route path="/forbidden" element={<ForbiddenPage/>}/><Route element={<RequireAuth/>}><Route element={<AppShell/>}><Route index element={<OverviewPage/>}/><Route path="generators" element={<GeneratorsPage/>}/><Route path="generators/:id" element={<GeneratorDetailPage/>}/><Route path="alarms" element={<AlarmsPage/>}/><Route path="events" element={<EventsPage/>}/><Route path="history" element={<HistoryPage/>}/><Route path="communication" element={<CommunicationPage/>}/><Route path="account/security" element={<SecurityPage/>}/><Route path="settings" element={<SettingsPage/>}/><Route path="about" element={<AboutPage/>}/><Route element={<RequirePermission permission="commissioning.read"/>}><Route path="engineering/commissioning" element={<CommissioningPage/>}/><Route path="engineering/commissioning/:id" element={<CommissioningDetailPage/>}/><Route path="engineering/profiles" element={<ProfilesPage/>}/><Route path="engineering/profiles/:profileId" element={<ProfileDetailPage/>}/><Route path="engineering/bindings" element={<BindingsPage/>}/></Route><Route element={<RequirePermission permission="commissioning.write"/>}><Route path="engineering/commissioning/new" element={<NewCommissioningPage/>}/><Route path="engineering/commissioning/:id/edit" element={<CommissioningEditPage/>}/></Route><Route element={<RequirePermission permission="diagnostics.read"/>}><Route path="engineering/diagnostics" element={<DiagnosticsPage/>}/></Route><Route element={<RequirePermission permission="users.read"/>}><Route path="admin/users" element={<UsersPage/>}/><Route path="admin/roles" element={<RolesPage/>}/></Route><Route element={<RequirePermission permission="sites.read"/>}><Route path="admin/sites" element={<SitesPage/>}/></Route><Route element={<RequirePermission permission="audit.read"/>}><Route path="admin/audit" element={<AuditPage/>}/></Route><Route element={<RequirePermission permission="system.read"/>}><Route path="admin/system" element={<SystemAdminPage/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Route></Route></Routes>}
